### PR TITLE
Added the command to run the server

### PR DESCRIPTION
**Pull request by ShadowMyst**
#Español/Spanish
Agregado el comando para correr el servidor en la parte de hasta abajo
#Ingles/English
Added the command to run the server in the up part

### CODE REVIEW

**Comment by muhammednagy** [comment]
This is completely wrong
You don't run the server in production
Nginx + passenger run it for you

**Comment by ShadowMyst** [comment]
Ok, so I'll work on it because I still can not get it to work with Nginx + passenger, but then I hope to solve that problem

**Comment by muhammednagy** [comment]
i can help if you need 
you can tell me what happens here

**Comment by ShadowMyst** [comment]
Although I have Nginx + passenger installed, I can not make it recognize the port 80 instead of the 3000 it has by default, although I already made the changes in config / application.yml and so I continued using the bundle exec rails server to start it

**Comment by muhammednagy** [comment]
can you how me the errors?show me nginx  config file

**Comment by ShadowMyst** [comment]
this?

**Pull request closed without merging**
