### PR TITLE
Adding the language in Spanish

### PR DESCRIPTION
**Pull request by ShadowMyst**
Hello muhammednagy, I am doing a pull request where I add the support in Spanish, although in itself the important thing is the last commit "67ad31c" where the locale is configured.

Only miss server.es.yml that are too many things to translate.

In addition to a correction in the locale in English

### CODE REVIEW

**Comment by muhammednagy** [comment]
Great work
can you finish server.es.yml  first? then we merge the pull request

**Comment by ShadowMyst** [comment]
Of course, I'm just working on it and apparently someone else will help me the same (although it will not be a complete translation, there are terms that it is better to keep in English)

**Comment by muhammednagy** [comment]
No problem to keep the terms that need to be in English 
i will be waiting 
i will close this pull request and feel free to open a new one when you finish that file

**Comment by ShadowMyst** [comment]
Ok, aunque también estoy trabajando en agregar ethereum y CREA

Jesús Figueroa (Shadow Myst)
http://shadowmyst.net

**Pull request closed without merging**
